version: "3"

services:
  tesseract:
    #image: zhenshaw/tesseract:ocr
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tesseract-ocr
    restart: always
    ports:
      - 8080:8080
    environment:
      - PORT=8080  # 如果rpc类型设置了all，会使用连续的三个端口
      - TOKEN=     # 指定访问token，默认空

#    volumes:
      # 内置的是eng的训练数据，如需其它，可挂载到改路径或修改Dockerfile
#      - tessdata_path:/usr/share/tesseract-ocr/4.00/tessdata