# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: capture.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='capture.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rcapture.proto\x12\x05proto\")\n\nOCRRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05token\x18\x02 \x01(\t\"\x18\n\x08OCRReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t2?\n\nCaptureOCR\x12\x31\n\tRecognize\x12\x11.proto.OCRRequest\x1a\x0f.proto.OCRReply\"\x00\x62\x06proto3'
)




_OCRREQUEST = _descriptor.Descriptor(
  name='OCRRequest',
  full_name='proto.OCRRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='proto.OCRRequest.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token', full_name='proto.OCRRequest.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=65,
)


_OCRREPLY = _descriptor.Descriptor(
  name='OCRReply',
  full_name='proto.OCRReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='proto.OCRReply.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['OCRRequest'] = _OCRREQUEST
DESCRIPTOR.message_types_by_name['OCRReply'] = _OCRREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OCRRequest = _reflection.GeneratedProtocolMessageType('OCRRequest', (_message.Message,), {
  'DESCRIPTOR' : _OCRREQUEST,
  '__module__' : 'capture_pb2'
  # @@protoc_insertion_point(class_scope:proto.OCRRequest)
  })
_sym_db.RegisterMessage(OCRRequest)

OCRReply = _reflection.GeneratedProtocolMessageType('OCRReply', (_message.Message,), {
  'DESCRIPTOR' : _OCRREPLY,
  '__module__' : 'capture_pb2'
  # @@protoc_insertion_point(class_scope:proto.OCRReply)
  })
_sym_db.RegisterMessage(OCRReply)



_CAPTUREOCR = _descriptor.ServiceDescriptor(
  name='CaptureOCR',
  full_name='proto.CaptureOCR',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=93,
  serialized_end=156,
  methods=[
  _descriptor.MethodDescriptor(
    name='Recognize',
    full_name='proto.CaptureOCR.Recognize',
    index=0,
    containing_service=None,
    input_type=_OCRREQUEST,
    output_type=_OCRREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CAPTUREOCR)

DESCRIPTOR.services_by_name['CaptureOCR'] = _CAPTUREOCR

# @@protoc_insertion_point(module_scope)
